# Example 4 - Using JS actions
name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs: # Using inputs
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The S3 bucket region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing deployable files.'
    required: true
outputs: # Using outputs
  website-url:
    description: 'Website URL of the AWS Bucket'
runs:
  using: 'node16' # Especify Node type action
  main: 'main.js'